sudo: false
language: python
python:
  - 3.6
install:
  - pip install -Ur requirements.txt
  - pip install -Ur ./tests/test_data/test_requirements.txt
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - "mv ./tests/test_data/.travis_postgres.json ./tests/test_data/postgres.json"
script:
  - flake8 minoshiro
  - pytest -v --capture=sys
notifications:
  email: false
  webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0ME1hVDFnM1IlM0FtYXRyaXgub3JnLyUyMU5EU0lMRkRhdUFHSFlDanV1dyUzQW1hdHJpeC5vcmc"
        on_success: always
        on_failure: always
        on_start: never
